In [2]:
import requests
import pandas as pd
from datetime import datetime

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"

all_records = []
start_year = datetime.now().year - 5   # last 5 years
end_year = datetime.now().year

for year in range(start_year, end_year + 1):
    for month in range(1, 13):
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        params = {
            "format": "geojson",
            "starttime": start_date,
            "endtime": end_date,
            "minmagnitude": 3
        }

        response = requests.get(url, params=params)
        if response.status_code != 200:
            print(f"⚠️ Failed for {start_date}: {response.text[:200]}")
            continue

        try:
            data = response.json()
        except Exception as e:
            print(f"⚠️ JSON error for {start_date}: {e}")
            continue

        for f in data["features"]:
            p = f["properties"]
            g = f["geometry"]["coordinates"]
            all_records.append({
                "id": f.get("id"),
                "time": pd.to_datetime(p.get("time"), unit="ms"),
                "updated": pd.to_datetime(p.get("updated"), unit="ms"),
                "latitude": g[1] if g else None,
                "longitude": g[0] if g else None,
                "depth_km": g[2] if g else None,
                "mag": p.get("mag"),
                "magType": p.get("magType"),
                "place": p.get("place"),
                "status": p.get("status"),
                "tsunami": p.get("tsunami"),
                "alert": p.get("alert"),
                "felt": p.get("felt"),
                "cdi": p.get("cdi"),
                "mmi": p.get("mmi"),
                "sig": p.get("sig"),
                "net": p.get("net"),
                "code": p.get("code"),
                "ids": p.get("ids"),
                "sources": p.get("sources"),
                "types": p.get("types"),
                "nst": p.get("nst"),
                "dmin": p.get("dmin"),
                "rms": p.get("rms"),
                "gap": p.get("gap"),
                "type": p.get("type")
  })

df = pd.DataFrame(all_records)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.head())

Rows: 112000
Columns: 26
           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...  net  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   us
1                                        Fiji region  reviewed  ...   us
2                    103 km SW of Basco, Philippines  reviewed  ...   us
3                            114 km N of M?n?b, Iran  reviewed  ...   us
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   us

       code           ids  sources                                   types  \
0  6000ddi8  ,us6000ddi8,     ,us,  ,dyfi,moment-tensor,origin,phase-data,
1  6000dev6  ,us6000dev6,     ,us,                     ,origin,phase-data,
2  6000dev5  ,us6000dev5,     ,us,                     ,origin,phase-data,
3  6000ddhs  ,us6000ddhs,     ,us,                     ,origin,phase-data,
4  6000dev4  ,us6000dev4,     ,us,                     ,origin,phase-data,

   nst   dmin   rms    gap        type
0  NaN  0.294  0.82   42.0  earthquake
1  NaN  1.471  0.29   64.0  earthquake
2  NaN  3.057  0.69  106.0  earthquake
3  NaN  3.330  0.61   71.0  earthquake
4  NaN  6.023  0.50   65.0  earthquake

[5 rows x 26 columns]

In [3]:
print(df.tail())

                   id                    time                 updated  \
111995     pr71515233 2026-05-01 02:13:24.250 2026-05-01 02:36:25.820
111996     nc75354667 2026-05-01 01:58:41.390 2026-05-01 05:57:21.998
111997  aka2026intneh 2026-05-01 01:26:59.448 2026-05-07 01:11:31.451
111998     pr71515218 2026-05-01 01:02:05.820 2026-05-01 01:21:41.770
111999     us7000shg3 2026-05-01 00:49:08.843 2026-05-17 21:32:59.040

         latitude   longitude  depth_km   mag magType  \
111995  18.548500  -66.297000     97.47  3.22      md
111996  40.301167 -124.572167      9.03  3.69      mw
111997  53.881000 -162.804000      0.30  3.00      ml
111998  19.161333  -66.767500     25.62  3.08      md
111999 -42.198400  -18.399600     10.00  5.00      mb

                                   place    status  ...  net         code  \
111995  10 km NNE of Brenas, Puerto Rico  reviewed  ...   pr     71515233
111996           24 km W of Petrolia, CA  reviewed  ...   nc     75354667
111997  115 km SSE of False Pass, Alaska  reviewed  ...   ak  a2026intneh
111998   74 km N of Hatillo, Puerto Rico  reviewed  ...   pr     71515218
111999       southern Mid-Atlantic Ridge  reviewed  ...   us     7000shg3

                            ids  sources  \
111995  ,us7000shgg,pr71515233,  ,us,pr,
111996  ,nc75354667,us7000shgd,  ,nc,us,
111997          ,aka2026intneh,     ,ak,
111998             ,pr71515218,     ,pr,
111999             ,us7000shg3,     ,us,

                                                    types   nst     dmin  \
111995                                ,origin,phase-data,  41.0   0.2318
111996  ,dyfi,moment-tensor,nearby-cities,origin,phase...  64.0   0.1761
111997                                ,origin,phase-data,  26.0   0.9000
111998                                ,origin,phase-data,  16.0   0.7170
111999                                ,origin,phase-data,  40.0  33.1140

         rms    gap        type
111995  0.20  188.0  earthquake
111996  0.22  239.0  earthquake
111997  0.50  247.0  earthquake
111998  0.11  258.0  earthquake
111999  0.71   66.0  earthquake

[5 rows x 26 columns]

In [5]:
print(100*(df.isnull().sum())/df.shape[0])

id            0.000000
time          0.000000
updated       0.000000
latitude      0.000000
longitude     0.000000
depth_km      0.000000
mag           0.000000
magType       0.000000
place         0.000000
status        0.000000
tsunami       0.000000
alert        95.909821
felt         84.621429
cdi          84.621429
mmi          91.430357
sig           0.000000
net           0.000000
code          0.000000
ids           0.000000
sources       0.000000
types         0.000000
nst          24.786607
dmin          3.548214
rms           0.016071
gap           2.697321
type          0.000000
dtype: float64

In [6]:
df[['alert','felt','mmi','cdi','nst']].dtypes

alert        str
felt     float64
mmi      float64
cdi      float64
nst      float64
dtype: object

In [7]:

df['alert']=df['alert'].str.lower()
df['alert'].unique()

<StringArray>
[nan, 'yellow', 'green', 'orange', 'red']
Length: 5, dtype: str

In [8]:
## for categorical data-replacing with Mode
df['alert'] = df['alert'].fillna(df['alert'].mode()[0])

In [9]:
## for high percentage of null values-Replacing with Median value
cols=['felt','cdi','mmi','nst']
df[cols]=df[cols].fillna(df[cols].median())

In [10]:
## for low percentage of null values-Replacing with Mean value
cols1=['gap','dmin','rms']
df[cols1]=df[cols1].fillna(df[cols1].mean())

In [11]:
## All Null values handled
print(100*(df.isnull().sum())/df.shape[0])

id           0.0
time         0.0
updated      0.0
latitude     0.0
longitude    0.0
depth_km     0.0
mag          0.0
magType      0.0
place        0.0
status       0.0
tsunami      0.0
alert        0.0
felt         0.0
cdi          0.0
mmi          0.0
sig          0.0
net          0.0
code         0.0
ids          0.0
sources      0.0
types        0.0
nst          0.0
dmin         0.0
rms          0.0
gap          0.0
type         0.0
dtype: float64

In [12]:
df[['ids','sources']]

                            ids  sources
0                  ,us6000ddi8,     ,us,
1                  ,us6000dev6,     ,us,
2                  ,us6000dev5,     ,us,
3                  ,us6000ddhs,     ,us,
4                  ,us6000dev4,     ,us,
...                         ...      ...
111995  ,us7000shgg,pr71515233,  ,us,pr,
111996  ,nc75354667,us7000shgd,  ,nc,us,
111997          ,aka2026intneh,     ,ak,
111998             ,pr71515218,     ,pr,
111999             ,us7000shg3,     ,us,

[112000 rows x 2 columns]

In [ ]:
df1=df.copy()
df1['sample']=df['ids'].str.strip(',').str.split(',')
df1['sample1']=df['sources'].str.strip(',').str.split(',')

In [29]:
df1['sample2']=df['types'].str.strip(',').str.split(',')

In [30]:
df1['sample']
df1['sample1']
df1['sample2']

0                 [dyfi, moment-tensor, origin, phase-data]
1                                      [origin, phase-data]
2                                      [origin, phase-data]
3                                      [origin, phase-data]
4                                      [origin, phase-data]
                                ...
111995                                 [origin, phase-data]
111996    [dyfi, moment-tensor, nearby-cities, origin, p...
111997                                 [origin, phase-data]
111998                                 [origin, phase-data]
111999                                 [origin, phase-data]
Name: sample2, Length: 112000, dtype: object

In [33]:
df1.columns
df1.shape

(112000, 26)

In [ ]:
df1=df1.drop(columns=(['ids','sources']))

In [32]:
df1=df1.drop(columns=('types'))

In [27]:
print(df1.head())

           id                    time                 updated  latitude  \
0  us6000ddi8 2021-01-31 23:20:49.923 2021-04-16 19:02:44.040  -31.7493
1  us6000dev6 2021-01-31 23:08:17.161 2021-04-16 19:03:47.040  -15.4902
2  us6000dev5 2021-01-31 22:54:19.760 2021-04-16 19:03:47.040   19.7529
3  us6000ddhs 2021-01-31 22:06:00.832 2021-04-16 19:02:43.040   28.1524
4  us6000dev4 2021-01-31 21:51:14.016 2021-04-16 19:03:46.040   71.3212

   longitude  depth_km  mag magType  \
0   -68.9337     17.27  4.7     mwr
1  -177.2052    426.71  4.1      mb
2   121.3159     46.73  4.7      mb
3    57.2570     10.00  4.9      mb
4    -3.7578     10.00  4.0      mb

                                               place    status  ...  net  \
0        29 km SW of Villa Basilio Nievas, Argentina  reviewed  ...   us
1                                        Fiji region  reviewed  ...   us
2                    103 km SW of Basco, Philippines  reviewed  ...   us
3                            114 km N of M?n?b, Iran  reviewed  ...   us
4  184 km ENE of Olonkinbyen, Svalbard and Jan Mayen  reviewed  ...   us

       code                                   types   nst   dmin   rms    gap  \
0  6000ddi8  ,dyfi,moment-tensor,origin,phase-data,  32.0  0.294  0.82   42.0
1  6000dev6                     ,origin,phase-data,  32.0  1.471  0.29   64.0
2  6000dev5                     ,origin,phase-data,  32.0  3.057  0.69  106.0
3  6000ddhs                     ,origin,phase-data,  32.0  3.330  0.61   71.0
4  6000dev4                     ,origin,phase-data,  32.0  6.023  0.50   65.0

         type        sample  sample1
0  earthquake  [us6000ddi8]     [us]
1  earthquake  [us6000dev6]     [us]
2  earthquake  [us6000dev5]     [us]
3  earthquake  [us6000ddhs]     [us]
4  earthquake  [us6000dev4]     [us]

[5 rows x 26 columns]

In [34]:
df1.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'nst', 'dmin', 'rms', 'gap', 'type', 'sample',
       'sample1', 'sample2'],
      dtype='str')

In [35]:
df1=df1.rename(columns={'sample':'ids'})
df1=df1.rename(columns={'sample1':'sources'})
df1=df1.rename(columns={'sample2':'types'})

In [36]:
df1.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'nst', 'dmin', 'rms', 'gap', 'type', 'ids',
       'sources', 'types'],
      dtype='str')

In [40]:
df1.loc[:,'status':'net']

          status  tsunami  alert  felt  cdi     mmi  sig net
0       reviewed        0  green  12.0  3.7  3.4135  344  us
1       reviewed        0  green   3.0  3.1  3.4135  259  us
2       reviewed        0  green   3.0  3.1  3.4135  340  us
3       reviewed        0  green   3.0  3.1  3.4135  369  us
4       reviewed        0  green   3.0  3.1  3.4135  246  us
...          ...      ...    ...   ...  ...     ...  ...  ..
111995  reviewed        0  green   3.0  3.1  3.4135  160  pr
111996  reviewed        0  green   2.0  2.0  2.5580  210  nc
111997  reviewed        0  green   3.0  3.1  3.4135  138  ak
111998  reviewed        0  green   3.0  3.1  3.4135  146  pr
111999  reviewed        0  green   3.0  3.1  3.4135  385  us

[112000 rows x 8 columns]

In [41]:
df1.alert.str.lower()

0         green
1         green
2         green
3         green
4         green
          ...
111995    green
111996    green
111997    green
111998    green
111999    green
Name: alert, Length: 112000, dtype: str

In [42]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 112000 entries, 0 to 111999
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         112000 non-null  str
 1   time       112000 non-null  datetime64[ms]
 2   updated    112000 non-null  datetime64[ms]
 3   latitude   112000 non-null  float64
 4   longitude  112000 non-null  float64
 5   depth_km   112000 non-null  float64
 6   mag        112000 non-null  float64
 7   magType    112000 non-null  str
 8   place      112000 non-null  str
 9   status     112000 non-null  str
 10  tsunami    112000 non-null  int64
 11  alert      112000 non-null  str
 12  felt       112000 non-null  float64
 13  cdi        112000 non-null  float64
 14  mmi        112000 non-null  float64
 15  sig        112000 non-null  int64
 16  net        112000 non-null  str
 17  code       112000 non-null  str
 18  nst        112000 non-null  float64
 19  dmin       112000 non-null  float64
 20  rms        112000 non-null  float64
 21  gap        112000 non-null  float64
 22  type       112000 non-null  str
 23  ids        112000 non-null  object
 24  sources    112000 non-null  object
 25  types      112000 non-null  object
dtypes: datetime64[ms](2), float64(11), int64(2), object(3), str(8)
memory usage: 22.2+ MB

In [45]:
df1['depth_km'].tolist()

[17.27,
 426.71,
 46.73,
 10.0,
 10.0,
 46.0,
 30.0,
 28.0,
 18.68,
 75.53,
 24.0,
 37.0,
 47.39,
 36.06,
 5.21,
 0.0,
 51.0,
 46.0,
 25.0,
 24.0,
 66.0,
 10.0,
 405.32,
 35.0,
 10.0,
 132.47,
 522.9,
 7.0,
 180.18,
 126.73,
 10.0,
 68.26,
 10.0,
 213.55,
 49.93,
 10.0,
 10.0,
 35.0,
 120.0,
 24.36,
 176.0,
 10.0,
 71.09,
 170.88,
 35.0,
 527.31,
 10.0,
 10.0,
 523.43,
 18.17,
 26.87,
 0.0,
 151.91,
 118.0,
 120.08,
 10.0,
 10.0,
 35.0,
 10.0,
 10.0,
 57.12,
 10.0,
 10.0,
 57.04,
 106.89,
 13.0,
 134.81,
 58.5,
 57.83,
 160.15,
 35.0,
 10.0,
 54.9,
 10.0,
 480.99,
 39.38,
 5.0,
 10.0,
 93.0,
 19.19,
 116.76,
 10.91,
 58.0,
 10.0,
 125.0,
 35.0,
 51.0,
 31.0,
 103.81,
 69.4,
 9.32,
 10.0,
 10.0,
 30.0,
 32.0,
 10.0,
 9.0,
 10.0,
 92.0,
 56.66,
 211.18,
 108.17,
 20.35,
 170.41,
 13.9,
 10.0,
 20.96,
 24.39,
 8.13,
 39.82,
 9.16,
 8.91,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 420.18,
 127.79,
 10.0,
 379.67,
 238.88,
 10.0,
 10.0,
 8.0,
 27.23,
 165.61,
 12.75,
 26.67,
 112.87,
 198.48,
 10.0,
 10.0,
 10.0,
 29.0,
 383.08,
 205.4,
 128.77,
 11.0,
 45.0,
 43.3,
 54.49,
 25.0,
 54.0,
 30.0,
 82.0,
 49.0,
 23.0,
 8.25,
 43.66,
 35.0,
 45.0,
 10.0,
 23.88,
 10.0,
 38.9,
 618.54,
 98.51,
 25.0,
 69.17,
 67.52,
 10.0,
 10.0,
 39.39,
 0.0,
 50.0,
 599.36,
 35.0,
 140.64,
 33.61,
 10.0,
 554.99,
 10.0,
 33.4,
 70.03,
 455.18,
 257.97,
 11.76,
 126.65,
 10.0,
 9.2,
 10.0,
 23.49,
 14.7,
 10.0,
 69.0,
 10.0,
 10.0,
 35.0,
 40.0,
 39.99,
 10.0,
 73.89,
 10.0,
 10.43,
 10.99,
 10.0,
 16.58,
 116.91,
 0.0,
 58.77,
 80.92,
 77.0,
 10.0,
 202.93,
 10.0,
 174.0,
 10.0,
 10.0,
 87.52,
 12.71,
 42.38,
 43.78,
 42.58,
 36.0,
 71.78,
 78.95,
 177.27,
 61.34,
 10.0,
 127.04,
 6.6,
 10.0,
 44.46,
 79.56,
 67.38,
 10.0,
 64.0,
 69.5,
 559.95,
 47.0,
 159.4,
 54.0,
 10.0,
 22.0,
 26.0,
 115.63,
 55.89,
 39.0,
 85.0,
 11.0,
 6.0,
 137.17,
 23.0,
 10.0,
 10.0,
 29.29,
 10.0,
 106.06,
 49.38,
 39.87,
 10.0,
 44.6,
 10.0,
 23.66,
 10.0,
 10.0,
 35.0,
 10.0,
 172.04,
 84.76,
 10.0,
 69.63,
 118.88,
 64.79,
 77.77,
 212.67,
 77.84,
 15.41,
 2.94,
 10.0,
 10.0,
 92.0,
 492.57,
 28.15,
 58.0,
 574.4,
 10.0,
 485.15,
 10.0,
 49.0,
 114.4,
 38.74,
 485.2,
 13.77,
 10.0,
 10.0,
 70.47,
 10.0,
 75.24,
 133.98,
 35.0,
 390.53,
 505.62,
 545.16,
 10.0,
 10.0,
 146.08,
 10.0,
 194.94,
 530.58,
 69.24,
 10.0,
 1.8,
 89.12,
 10.0,
 46.94,
 10.72,
 10.0,
 6.0,
 92.11,
 211.0,
 10.0,
 10.0,
 30.2,
 90.63,
 10.0,
 537.09,
 10.0,
 70.36,
 38.32,
 26.8,
 36.13,
 57.29,
 10.0,
 586.05,
 57.99,
 10.0,
 10.0,
 29.51,
 521.43,
 10.0,
 102.24,
 177.8,
 5.0,
 15.6,
 10.0,
 10.0,
 10.0,
 10.0,
 48.07,
 98.52,
 10.0,
 10.0,
 10.0,
 61.0,
 10.0,
 10.0,
 12.0,
 376.77,
 25.71,
 34.0,
 22.9,
 94.0,
 3.3,
 10.0,
 10.0,
 10.0,
 256.88,
 46.69,
 62.63,
 39.38,
 10.0,
 10.0,
 140.99,
 226.63,
 10.0,
 117.26,
 10.0,
 23.79,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 64.31,
 35.0,
 10.0,
 10.0,
 193.89,
 54.96,
 10.0,
 10.0,
 97.56,
 20.27,
 10.0,
 103.97,
 10.0,
 17.94,
 10.0,
 168.83,
 96.0,
 10.0,
 10.0,
 10.0,
 10.0,
 363.75,
 341.63,
 10.0,
 10.0,
 10.0,
 74.69,
 10.0,
 166.86,
 8.4,
 102.53,
 35.0,
 35.0,
 220.81,
 49.61,
 502.82,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 102.89,
 10.0,
 109.48,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 15.0,
 10.0,
 10.0,
 199.47,
 25.07,
 42.2,
 10.0,
 2.68,
 18.04,
 518.77,
 61.46,
 35.1,
 96.0,
 202.06,
 10.0,
 44.15,
 72.56,
 419.23,
 430.69,
 35.2,
 185.52,
 53.6,
 10.0,
 10.0,
 10.0,
 165.55,
 35.0,
 14.93,
 38.55,
 30.01,
 32.79,
 104.0,
 525.52,
 10.0,
 55.72,
 108.19,
 9.99,
 35.0,
 139.38,
 19.0,
 10.0,
 43.98,
 64.0,
 27.0,
 37.94,
 10.0,
 10.0,
 10.0,
 57.53,
 140.0,
 10.0,
 10.0,
 39.31,
 10.0,
 10.0,
 30.58,
 117.91,
 220.41,
 30.84,
 10.0,
 89.0,
 34.0,
 36.16,
 81.04,
 601.24,
 47.93,
 37.99,
 132.64,
 10.0,
 8.7,
 113.3,
 191.45,
 32.96,
 40.89,
 10.0,
 117.45,
 34.0,
 59.84,
 10.0,
 190.08,
 22.0,
 22.04,
 47.0,
 220.04,
 10.0,
 10.0,
 47.0,
 35.0,
 41.0,
 53.39,
 57.0,
 42.0,
 69.0,
 187.17,
 20.0,
 10.0,
 10.0,
 10.0,
 155.9,
 15.44,
 57.91,
 169.29,
 39.0,
 10.0,
 36.0,
 10.0,
 121.87,
 55.0,
 63.91,
 10.0,
 56.0,
 36.0,
 24.44,
 10.0,
 10.0,
 13.0,
 90.29,
 4.0,
 4.0,
 109.94,
 25.84,
 104.0,
 76.78,
 20.0,
 144.74,
 10.0,
 556.18,
 100.34,
 10.0,
 102.31,
 199.15,
 120.51,
 5.0,
 10.0,
 114.83,
 62.88,
 115.6,
 10.0,
 56.0,
 5.2,
 20.89,
 86.72,
 117.63,
 8.2,
 80.0,
 58.0,
 10.0,
 90.2,
 70.94,
 10.0,
 308.73,
 10.0,
 574.94,
 22.15,
 10.0,
 11.6,
 10.0,
 48.32,
 211.32,
 153.8,
 16.0,
 8.0,
 23.0,
 10.0,
 10.0,
 10.0,
 35.0,
 105.77,
 54.23,
 10.0,
 137.0,
 181.41,
 22.26,
 21.2,
 3.23,
 3.0,
 57.1,
 10.0,
 43.0,
 2.8,
 10.0,
 10.0,
 10.0,
 5.29,
 10.0,
 13.19,
 18.89,
 0.0,
 128.86,
 61.18,
 82.37,
 19.76,
 587.39,
 10.0,
 37.0,
 10.0,
 16.0,
 10.0,
 40.98,
 38.12,
 163.09,
 35.0,
 16.0,
 19.55,
 483.28,
 39.0,
 28.47,
 6.39,
 97.95,
 10.0,
 5.0,
 192.76,
 29.0,
 60.49,
 55.0,
 34.0,
 30.0,
 127.0,
 66.0,
 34.0,
 10.0,
 53.3,
 37.0,
 58.0,
 533.36,
 55.62,
 133.0,
 52.0,
 10.0,
 110.46,
 10.0,
 10.0,
 10.0,
 42.53,
 5.0,
 31.0,
 10.0,
 10.0,
 10.0,
 75.81,
 41.0,
 48.96,
 35.0,
 276.88,
 10.0,
 234.78,
 90.0,
 40.82,
 92.06,
 81.72,
 556.07,
 27.61,
 25.0,
 165.47,
 7.4,
 10.0,
 33.0,
 62.0,
 119.02,
 77.0,
 78.0,
 71.0,
 77.0,
 146.2,
 7.0,
 31.0,
 10.0,
 72.08,
 10.0,
 553.68,
 136.77,
 10.0,
 26.76,
 63.0,
 158.78,
 10.0,
 65.0,
 501.99,
 24.54,
 10.0,
 16.14,
 10.0,
 10.0,
 36.0,
 33.0,
 428.11,
 66.0,
 150.93,
 38.0,
 42.0,
 10.0,
 10.0,
 10.0,
 87.58,
 10.0,
 10.0,
 34.0,
 20.81,
 35.0,
 23.97,
 24.26,
 45.46,
 79.29,
 10.0,
 10.0,
 514.81,
 54.0,
 104.43,
 15.0,
 28.78,
 166.3,
 10.0,
 0.0,
 23.52,
 -0.27,
 59.32,
 10.0,
 8.21,
 10.0,
 15.0,
 10.0,
 10.0,
 10.0,
 579.33,
 10.0,
 24.82,
 154.12,
 10.0,
 35.67,
 96.0,
 43.43,
 10.0,
 10.0,
 224.75,
 10.0,
 10.0,
 11.8,
 133.8,
 231.94,
 577.09,
 148.54,
 60.28,
 89.0,
 557.58,
 100.0,
 2.82,
 161.55,
 32.77,
 7.7,
 10.0,
 77.45,
 42.0,
 14.0,
 161.04,
 104.8,
 119.59,
 606.87,
 163.27,
 325.99,
 10.0,
 547.74,
 45.0,
 13.24,
 106.18,
 59.0,
 16.0,
 158.06,
 128.22,
 24.0,
 207.55,
 61.93,
 34.0,
 16.0,
 10.0,
 27.0,
 51.0,
 24.0,
 578.07,
 25.0,
 125.81,
 167.55,
 548.09,
 48.76,
 94.17,
 220.11,
 64.0,
 31.0,
 27.0,
 22.0,
 27.0,
 42.44,
 79.0,
 9.0,
 10.0,
 10.0,
 23.04,
 158.58,
 85.7,
 10.0,
 14.72,
 100.9,
 157.86,
 157.46,
 23.0,
 10.0,
 147.05,
 10.0,
 10.0,
 8.32,
 10.0,
 180.77,
 73.12,
 0.96,
 1.52,
 10.0,
 1.11,
 28.0,
 10.0,
 24.0,
 78.5,
 16.0,
 10.0,
 31.81,
 10.0,
 17.66,
 101.14,
 74.69,
 14.61,
 80.23,
 10.0,
 61.32,
 21.43,
 26.56,
 204.0,
 10.0,
 67.0,
 53.55,
 10.0,
 35.0,
 14.2,
 89.0,
 20.87,
 15.74,
 350.63,
 10.0,
 36.47,
 39.75,
 136.69,
 35.0,
 38.62,
 102.23,
 10.0,
 22.0,
 5.0,
 52.62,
 4.72,
 4.0,
 6.11,
 130.17,
 3.36,
 5.95,
 210.97,
 10.0,
 10.0,
 49.25,
 58.84,
 35.0,
 10.0,
 214.85,
 10.0,
 90.99,
 10.0,
 114.0,
 35.45,
 23.85,
 61.18,
 10.0,
 10.0,
 10.0,
 95.6,
 158.64,
 7.68,
 24.3,
 8.0,
 200.31,
 10.0,
 22.64,
 0.0,
 4.0,
 10.0,
 228.72,
 10.0,
 27.53,
 10.0,
 4.0,
 38.88,
 10.0,
 10.0,
 10.0,
 69.52,
 10.0,
 21.0,
 10.0,
 27.06,
 10.2,
 48.71,
 10.0,
 101.89,
 33.92,
 359.74,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 35.0,
 10.0,
 38.16,
 37.18,
 10.0,
 62.59,
 67.0,
 74.0,
 222.4,
 10.0,
 10.0,
 10.0,
 10.0,
 10.0,
 123.0,
 10.0,
 10.0,
 557.55,
 34.06,
 633.3,
 32.87,
 139.14,
 15.0,
 23.0,
 10.0,
 10.0,
 625.83,
 10.0,
 56.6,
 0.0,
 219.39,
 10.0,
 44.0,
 133.92,
 10.0,
 10.0,
 15.24,
 38.0,
 18.0,
 0.0,
 116.0,
 252.66,
 46.0,
 10.0,
 11.4,
 10.0,
 118.25,
 20.41,
 10.0,
 550.65,
 110.14,
 48.35,
 283.7,
 10.0,
 22.04,
 10.0,
 34.0,
 68.18,
 ...]

In [46]:
df1['depth_km'].describe()

count    112000.000000
mean         71.914553
std         123.411883
min          -3.740000
25%          10.000000
50%          21.406000
75%          71.100000
max         683.578000
Name: depth_km, dtype: float64

In [49]:
def classify_depth(depth):
    if depth < 100:
        return 'Shallow'
    else:
        return 'Deep'

df1['Earthquake_flags'] = df1['depth_km'].apply(classify_depth)

In [50]:
df1['Earthquake_flags']

0         Shallow
1            Deep
2         Shallow
3         Shallow
4         Shallow
           ...
111995    Shallow
111996    Shallow
111997    Shallow
111998    Shallow
111999    Shallow
Name: Earthquake_flags, Length: 112000, dtype: str

In [59]:
df1=df1.drop(columns='Earthquake_flag')

In [53]:
df['mag']
df['mag'].describe()

count    112000.000000
mean          4.256637
std           0.609649
min           3.000000
25%           4.000000
50%           4.300000
75%           4.600000
max           8.800000
Name: mag, dtype: float64

In [55]:
df1['Destructive_flag']=df['mag'].apply(lambda x: 'Destructive' if x>=6 else 'Strong')

In [60]:
df1.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'alert', 'felt', 'cdi', 'mmi',
       'sig', 'net', 'code', 'nst', 'dmin', 'rms', 'gap', 'type', 'ids',
       'sources', 'types', 'Earthquake_flags', 'Destructive_flag'],
      dtype='str')

In [61]:
df1['Year']=pd.to_datetime(df1['time']).dt.year

In [62]:
df1['Month']=pd.to_datetime(df1['time']).dt.month
df1['Day']=pd.to_datetime(df1['time']).dt.day
df1['Day_of_week']=pd.to_datetime(df1['time']).dt.day_of_week

In [68]:
df1.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,type,ids,sources,types,Earthquake_flags,Destructive_flag,Year,Month,Day,Day_of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,earthquake,['us6000ddi8'],['us'],"['dyfi', 'moment-tensor', 'origin', 'phase-data']",Shallow,Strong,2021,1,31,6
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,earthquake,['us6000dev6'],['us'],"['origin', 'phase-data']",Deep,Strong,2021,1,31,6
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,earthquake,['us6000dev5'],['us'],"['origin', 'phase-data']",Shallow,Strong,2021,1,31,6
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,earthquake,['us6000ddhs'],['us'],"['origin', 'phase-data']",Shallow,Strong,2021,1,31,6
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,earthquake,['us6000dev4'],['us'],"['origin', 'phase-data']",Shallow,Strong,2021,1,31,6

In [ ]:
df1['sources'] = df1['sources'].str.strip('[]').str.replace("'", "")

In [71]:
df1['ids'] = df1['ids'].str.strip('[]').str.replace("'", "")
df1['types'] = df1['types'].str.strip('[]').str.replace("'", "")

In [72]:
df1.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,type,ids,sources,types,Earthquake_flags,Destructive_flag,Year,Month,Day,Day_of_week
0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",reviewed,...,earthquake,us6000ddi8,us,"dyfi, moment-tensor, origin, phase-data",Shallow,Strong,2021,1,31,6
1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,reviewed,...,earthquake,us6000dev6,us,"origin, phase-data",Deep,Strong,2021,1,31,6
2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",reviewed,...,earthquake,us6000dev5,us,"origin, phase-data",Shallow,Strong,2021,1,31,6
3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",reviewed,...,earthquake,us6000ddhs,us,"origin, phase-data",Shallow,Strong,2021,1,31,6
4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",reviewed,...,earthquake,us6000dev4,us,"origin, phase-data",Shallow,Strong,2021,1,31,6

In [70]:
df1['sources']

0             us
1             us
2             us
3             us
4             us
           ...
111995    us, pr
111996    nc, us
111997        ak
111998        pr
111999        us
Name: sources, Length: 112000, dtype: str

In [66]:
list_cols = ['ids', 'sources', 'types']

for col in list_cols:
    df1[col] = df1[col].astype(str)

In [64]:

import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Vehapraha%402010@localhost:3306/first_proj"
)

In [73]:
df1.to_sql(
    name='earthquake_info',
    con=engine,
    if_exists='replace',
    index=False
)

112000

In [9]:
%pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\Users\info\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in c:\Users\info\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.1.3)
Requirement already satisfied: greenlet>=1 in c:\Users\info\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\info\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111939 entries, 0 to 111938
Data columns (total 26 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   id         111939 non-null  str
 1   time       111939 non-null  datetime64[ms]
 2   updated    111939 non-null  datetime64[ms]
 3   latitude   111939 non-null  float64
 4   longitude  111939 non-null  float64
 5   depth_km   111939 non-null  float64
 6   mag        111939 non-null  float64
 7   magType    111939 non-null  str
 8   place      111939 non-null  str
 9   status     111939 non-null  str
 10  tsunami    111939 non-null  int64
 11  alert      111939 non-null  str
 12  felt       111939 non-null  float64
 13  cdi        111939 non-null  float64
 14  mmi        111939 non-null  float64
 15  sig        111939 non-null  int64
 16  net        111939 non-null  str
 17  code       111939 non-null  str
 18  ids        111939 non-null  str
 19  sources    111939 non-null  str
 20  types      111939 non-null  str
 21  nst        111939 non-null  float64
 22  dmin       111939 non-null  float64
 23  rms        111939 non-null  float64
 24  gap        111939 non-null  float64
 25  type       111939 non-null  str
dtypes: datetime64[ms](2), float64(11), int64(2), str(11)
memory usage: 22.2 MB

In [41]:
df.loc[:,'sources':'gap']

,sources,types,nst,dmin,rms,gap
0,",us,",",dyfi,moment-tensor,origin,phase-data,",32.0,0.2940,0.82,42.0
1,",us,",",origin,phase-data,",32.0,1.4710,0.29,64.0
2,",us,",",origin,phase-data,",32.0,3.0570,0.69,106.0
3,",us,",",origin,phase-data,",32.0,3.3300,0.61,71.0
4,",us,",",origin,phase-data,",32.0,6.0230,0.50,65.0
...,...,...,...,...,...,...
111934,",us,pr,",",origin,phase-data,",41.0,0.2318,0.20,188.0
111935,",nc,us,",",dyfi,moment-tensor,nearby-cities,origin,phase...",64.0,0.1761,0.22,239.0
111936,",ak,",",origin,phase-data,",26.0,0.9000,0.50,247.0
111937,",pr,",",origin,phase-data,",16.0,0.7170,0.11,258.0
111938,",us,",",origin,phase-data,",40.0,33.1140,0.71,66.0

In [43]:
df['nst','dmin', 'rms', 'gap', 'magError', 'depthError', 'magNst', 'sig'].dtypes

KeyError: ('nst', 'dmin', 'rms', 'gap', 'magError', 'depthError', 'magNst', 'sig')